### ISSUE TITLE
Correct configuration

### ISSUE THREAD

**Issue by ghost** [zeroq/amun#8]
What is the correct configuration for the server's IP address? 0.0.0.0 or server's IP?

```
[AmunServer]

### define the amun server ip
ip: 0.0.0.0
#ip: 192.168.0.1 - 192.168.0.5, 192.168.15.1 - 192.168.15.15
#ip: 192.168.0.1, 192.168.0.2, 192.168.0.5
#ip: 192.168.0.0/28
#ip: eth0
```
I ask because Amun probably does not work. How can I check if Amun is functioning properly?

**Comment by zeroq** [comment]
Hi, no problem. The predefined IP 0.0.0.0 will enable Amun to listen on all IP addresses that are configured for the system. If you only want Amun to listen on a specific IP address then set the appropriate one here.

In order to test if Amun itself is running you might browse to port 80 on your server, because Amun is also simulating a basic webserver. Other testing could be done using simply telnet to connect to a port belonging to Amun.

Hope it helps.
